name: linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python Linter for app
      uses: sunnysid3up/python-linter@master
      with:
        source: "app_python/app"
        mypy-options: "--ignore-missing-imports --show-error-codes"
        pylint-options: "--rcfile=setup.cfg"
        isort-options: "-w 100"
        django: true
    - name: Python Linter for tests
      uses: sunnysid3up/python-linter@master
      with:
        source: "app_python/test"
        mypy-options: "--ignore-missing-imports --show-error-codes"
        pylint-options: "--rcfile=setup.cfg"
        isort-options: "-w 100"
        django: true